// Command generate-abyss-combat-catalog exports initialized runtime identities
// for combat graphics without changing the existing static icon sheets.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"ts3news/internal/content"
	"ts3news/internal/i18n"
)

type combatIdentity struct {
	Name    string `json:"name"`
	Kind    string `json:"kind"`
	Family  string `json:"family"`
	Element string `json:"element,omitempty"`
	Variant string `json:"variant,omitempty"`
}

func main() {
	check := flag.Bool("check", false, "verify the checked-in combat catalog is current")
	flag.Parse()
	if err := i18n.InitWithLocale(i18n.LocaleEnUS); err != nil {
		log.Fatal(err)
	}
	content.InitLocalized()
	manifest := make(map[string]combatIdentity)
	counts := make(map[string]int)
	for _, entry := range content.PixelArtCatalog() {
		manifest[entry.Key] = combatIdentity{
			Name: entry.Name, Kind: entry.Kind, Family: entry.Family,
			Element: entry.Element, Variant: entry.Variant,
		}
		counts[entry.Kind]++
	}
	for _, source := range []struct{ file, variable string }{
		{"abyss_double_boss.go", "abyssBossRoster"},
		{"abyss_boss_lore.go", "abyssBossLoreCatalog"},
		{"abyss_secret_boss_chain.go", "abyssSecretBosses"},
	} {
		if err := addBosses(manifest, filepath.Join("internal", "bot", source.file), source.variable); err != nil {
			log.Fatal(err)
		}
	}
	encoded, err := json.Marshal(manifest)
	if err != nil {
		log.Fatal(err)
	}
	output := append([]byte("// Generated by go run ./cmd/generate-abyss-combat-catalog; locale initialized before enumeration.\r\nwindow.AB_COMBAT_CATALOG="), encoded...)
	output = append(output, []byte(";\r\n")...)
	filename := filepath.Join("internal", "bot", "webassets", "abyss_combat_catalog.js")
	if *check {
		existing, err := os.ReadFile(filename)
		if err != nil {
			log.Fatal(err)
		}
		if !bytes.Equal(existing, output) {
			log.Fatal("combat catalog changed; run go run ./cmd/generate-abyss-combat-catalog")
		}
	} else if err := os.WriteFile(filename, output, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Combat catalog: %d identities, %d skills, %d ultimates, %d monsters, %d pet types, %d gear, %d consumables, %d artifacts\n",
		len(manifest), counts["skill"], counts["ultimate"], counts["monster"], counts["pet"],
		counts["gear"], counts["consumable"], counts["artifact"])
}

// Read authoritative literal boss catalogs without importing bot startup code.
func addBosses(manifest map[string]combatIdentity, filename, variable string) error {
	file, err := parser.ParseFile(token.NewFileSet(), filename, nil, 0)
	if err != nil {
		return fmt.Errorf("read boss catalog %s: %w", filename, err)
	}
	found := false
	ast.Inspect(file, func(node ast.Node) bool {
		definition, ok := node.(*ast.ValueSpec)
		if !ok {
			return true
		}
		for _, name := range definition.Names {
			if name.Name != variable {
				continue
			}
			found = true
			ast.Inspect(definition, func(child ast.Node) bool {
				if field, ok := child.(*ast.KeyValueExpr); ok {
					key, ok := field.Key.(*ast.Ident)
					if !ok || (key.Name != "Name" && key.Name != "Boss") {
						return false
					}
				}
				literal, ok := child.(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					return true
				}
				boss, err := strconv.Unquote(literal.Value)
				if err == nil && strings.TrimSpace(boss) != "" {
					manifest["monster:"+boss] = combatIdentity{
						Name: boss, Kind: "monster", Family: "bosses", Variant: "AbyssBoss",
					}
				}
				return false
			})
		}
		return false
	})
	if !found {
		return fmt.Errorf("boss catalog %s is missing %s", filename, variable)
	}
	return nil
}
