const {test,expect}=require('@playwright/test');
test('campaign filters and matching missions survive failed reads and recovery',async({page})=>{
 await page.goto('/abyss/rift');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-favorite').click();await page.locator('#rift-region').selectOption('0');await page.locator('#rift-completion').selectOption('unfinished');await page.locator('#rift-difficulty').selectOption('Wayfarer');await page.locator('#rift-mission-search').fill('1');await page.locator('#rift-favorites-only').check();await page.locator('#rift-compact').check();await page.locator('#rift-mission-sort').selectOption('best');
 await page.locator('details.rift-bestiary > summary').click();await page.locator('#rift-monster-search').fill('boss');
 for(const id of ['family','tier','element','style']){const node=page.locator('#rift-monster-'+id);await node.selectOption(await node.locator('option').nth(1).getAttribute('value'));}
 await page.locator('#rift-monster-bookmarked').check();await page.locator('#rift-monster-seen').check();
 const view=()=>page.evaluate(()=>({search:document.getElementById('rift-mission-search').value,region:document.getElementById('rift-region').value,completion:document.getElementById('rift-completion').value,difficulty:document.getElementById('rift-difficulty').value,favorites:document.getElementById('rift-favorites-only').checked,compact:document.getElementById('rift-compact').checked,sort:document.getElementById('rift-mission-sort').value,monsterFilters:['search','family','tier','element','style'].map(id=>document.getElementById('rift-monster-'+id).value),monsterFlags:['bookmarked','seen'].map(id=>document.getElementById('rift-monster-'+id).checked),monsterMatches:[...document.querySelectorAll('#rift-monsters > *')].filter(n=>!n.hidden).map(n=>n.dataset.artKey),matches:[...document.querySelectorAll('#rift-levels [data-level]')].filter(n=>!n.hidden).map(n=>n.dataset.level)}));
 const before=await view();expect(before.matches).toEqual(['1']);let startFailed=false,readFailed=false;
 await page.route('**/api/abyss/rift',route=>{if(route.request().method()==='POST'&&!startFailed){startFailed=true;return route.fulfill({status:500,body:'unavailable'});}if(route.request().method()==='GET'&&startFailed&&!readFailed){readFailed=true;return route.fulfill({status:500,body:'unavailable'});}return route.continue();});
 await page.locator('#rift-start').click();await expect(page.locator('#rift-start')).toHaveText('Recover expedition');await page.locator('#rift-start').click();await expect(page.locator('#rift-start')).toHaveText('Retry loading');expect(await view()).toEqual(before);
 await page.locator('#rift-start').click();await expect(page.locator('#rift-start')).toHaveText('Enter the ruins →');expect(await view()).toEqual(before);
});
