const {test,expect}=require('@playwright/test');
test('loot compares raw stats against saved same-slot gear and handles empty or legacy snapshots',async({page})=>{
 await page.goto('/abyss/rift?scenario=checkpoint');await expect(page.locator('#rift-start')).toBeEnabled();const saved=(await(await page.request.get('/api/abyss/rift')).json()).run;
 const show=async(equipment)=>page.evaluate(({saved,equipment})=>{const run=structuredClone(saved);run.build.equipment=equipment;run.drops=[{id:'comparison',x:100,y:400,gold:0,collected:true,banked:false,gear:{ID:'comparison-gear',Name:'Trial sword',Slot:'MainHand',Rarity:1,MaxDurability:100,Stats:{STR:25,HP:0,DEF:3}}}];RiftLoot.update(run,true);},{saved,equipment});
 await show({MainHand:{name:'Old sword',stats:{STR:20,HP:10,DEF:3}},Head:{name:'Wrong slot',stats:{STR:900}}});const item=page.locator('#rift-loot > li > details');await item.locator(':scope > summary').click();const comparison=page.locator('.rift-gear-comparison');await comparison.locator('summary').click();await expect(comparison).toContainText('Against Old sword');await expect(comparison).toContainText('STR +5');await expect(comparison).toContainText('HP -10');await expect(comparison).not.toContainText('Wrong slot');await expect(comparison).toContainText('not predicted Brawl damage');
 await page.setViewportSize({width:390,height:1600});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await comparison.scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollBy(0,-240));await comparison.screenshot({path:'test-results/gear-comparison-mobile.png'});
 await show({});await item.locator(':scope > summary').click();await comparison.locator('summary').click();await expect(comparison).toContainText('No item equipped');await expect(comparison).toContainText('STR +25');
 await show(null);await item.locator(':scope > summary').click();await comparison.locator('summary').click();await expect(comparison).toContainText('Comparison unavailable');
 await show({MainHand:{name:'Equal sword',stats:{STR:25,HP:0,DEF:3}}});await item.locator(':scope > summary').click();await comparison.locator('summary').click();await expect(comparison).toContainText('No base stat changes');expect((await(await page.request.get('/api/abyss/rift')).json()).run).toEqual(saved);
});
