const {test,expect}=require('@playwright/test');
test('foundation missing signatures explain actual unlock steps and saved-build timing',async({page})=>{
 await page.goto('/abyss/rift?scenario=checkpoint');await expect(page.locator('#rift-start')).toBeEnabled();
 await page.route('**/api/abyss/rift',async route=>{const response=await route.fetch(),data=await response.json();for(const build of [data.build,data.run?.build].filter(Boolean)){build.class='warrior';build.base_class='warrior';build.signatures=[];}await route.fulfill({response,json:data});});await page.evaluate(()=>history.replaceState(null,'','/abyss/rift'));await page.reload();
 const help=page.locator('#rift-signature-help');await expect(help).toBeVisible();await expect(help).toContainText('first class point');await expect(help).toContainText('three class points');await expect(help).toContainText('five foundation talent points');await expect(help).toContainText('Start a new Brawl expedition');await expect(page.locator('#rift-signature-help-link')).toHaveAttribute('href','/abyss#abyssMyBuild');await expect(page.locator('#rift-start')).toBeEnabled();
 await page.setViewportSize({width:390,height:1600});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#rift-class-primer').scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollBy(0,-240));await page.locator('#rift-class-primer').screenshot({path:'test-results/signature-help-mobile.png'});
});
test('signature guidance distinguishes partial and subclass builds, and hides when complete',async({page})=>{
 await page.goto('/abyss/rift?scenario=checkpoint');await expect(page.locator('#rift-start')).toBeEnabled();await expect(page.locator('#rift-signature-help')).toBeHidden();await expect(page.locator('#rift-signature-help-link')).toBeHidden();
 const text=await page.evaluate(()=>({partial:RiftAbilities.signatureHelp({class:'warrior',base_class:'warrior',signatures:[{role:'builder'}]}),subclass:RiftAbilities.signatureHelp({class:'vanguard',base_class:'warrior',signatures:[]}),complete:RiftAbilities.signatureHelp({signatures:[{role:'builder'},{role:'finisher'}]})}));expect(text.partial).toContain('Finisher is missing');expect(text.partial).not.toContain('first class point');expect(text.subclass).toContain('Check your selected subclass');expect(text.subclass).not.toContain('unlock a subclass');expect(text.complete).toBe('');
});
