const {test,expect}=require('@playwright/test');
for(const reduced of [false,true])test('bank success feedback waits for confirmation and deduplicates receipts (reduced '+reduced+')',async({page})=>{
 await page.goto('/abyss/rift?scenario=checkpoint');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();await page.evaluate(reduced=>{RiftRenderer.reduced=reduced;window.bankSounds=0;const play=RiftAudio.play;RiftAudio.play=(...args)=>{if(args[0]==='bank')bankSounds++;return play(...args);};window.bankAnimations=0;const node=document.getElementById('rift-banked'),animate=node.animate.bind(node);node.animate=(...args)=>{bankAnimations++;return animate(...args);};},reduced);
 const before=(await(await page.request.get('/api/abyss/rift')).json()).run;let release,observe;const held=new Promise(resolve=>release=resolve),pending=new Promise(resolve=>observe=resolve);
 await page.route('**/api/abyss/rift',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().kind==='exit'){observe();await held;}await route.continue();});await page.locator('#rift-start').click();await page.locator('#rift-exit').click();await pending;
 expect(await page.evaluate(()=>bankSounds)).toBe(0);expect(await page.evaluate(()=>bankAnimations)).toBe(0);await expect(page.locator('#rift-banked')).not.toHaveAttribute('data-bank-confirmed','true');release();await expect.poll(()=>page.evaluate(()=>bankSounds)).toBe(1);expect(await page.evaluate(()=>bankAnimations)).toBe(reduced?0:1);
 const after=(await(await page.request.get('/api/abyss/rift')).json()).run;
 expect(await page.evaluate(({before,after})=>[RiftLoot.confirmBank(before,after),RiftLoot.confirmBank(after,after),RiftLoot.confirmBank(after,before)],{before,after})).toEqual([false,false,false]);expect(await page.evaluate(()=>bankSounds)).toBe(1);
});
test('uncertain committed banking and read recovery do not celebrate success',async({page})=>{
 await page.goto('/abyss/rift?scenario=checkpoint');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();await page.evaluate(()=>{window.bankSounds=0;const play=RiftAudio.play;RiftAudio.play=(...args)=>{if(args[0]==='bank')bankSounds++;return play(...args);};});
 await page.route('**/api/abyss/rift',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().kind==='exit'){await route.fetch();await route.abort('failed');}else await route.continue();});await page.locator('#rift-start').click();await page.locator('#rift-exit').click();await expect(page.locator('#rift-start')).toHaveText('Recover expedition');expect(await page.evaluate(()=>bankSounds)).toBe(0);await page.locator('#rift-start').click();await expect(page.locator('#rift-banking-status')).toContainText('Saved reward state loaded');expect(await page.evaluate(()=>bankSounds)).toBe(0);await expect(page.locator('#rift-banked')).not.toHaveAttribute('data-bank-confirmed','true');
});
