const {test,expect}=require('@playwright/test');
test('clear patrol, reset wrong rune, reload and open gate with WASD and jump',async({page})=>{
 test.setTimeout(120000);await page.goto('/abyss/rift?scenario=rune_gate');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();
 const saved=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run,progress=page.locator('#rift-room-objective-progress');
 const hook=()=>page.evaluate(()=>{window.gateCues=[];const play=window.RiftAudio.play;window.RiftAudio.play=function(kind,...args){if(kind.startsWith('rune_'))window.gateCues.push(kind);return play.call(this,kind,...args);};});
 await hook();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();await expect(progress).toContainText('Defeat the patrol');await page.keyboard.press('KeyJ');await expect(progress).toContainText('Next seal:');expect((await saved()).level.rooms[0].hazards.every(h=>h.disabled)).toBe(true);
 // Contact is transient: a queued movement tick can leave the rune after keyup.
 // Observe contact in the authoritative loop; callers assert persistent progress and cues.
 const visit=async id=>{const target=(await saved()).room_objective.pickups.find(p=>p.id===id),held=new Set();let touched=false;try{for(let n=0;n<500;n++){const r=await saved(),dx=target.x-r.player.x,dy=target.y-r.player.y;if(r.room_objective.puzzle_touch===id){touched=true;break;}const wanted=new Set();if(Math.hypot(dx,dy)>100)wanted.add('Space');if(Math.abs(dx)>8)wanted.add(dx>0?'KeyD':'KeyA');if(Math.abs(dy)>8)wanted.add(dy>0?'KeyS':'KeyW');for(const key of held)if(!wanted.has(key)){await page.keyboard.up(key);held.delete(key);}for(const key of wanted)if(!held.has(key)){await page.keyboard.down(key);held.add(key);}await page.waitForTimeout(Math.hypot(dx,dy)<100?120:40);}}finally{for(const key of held)await page.keyboard.up(key);}expect(touched,'server confirmed rune contact').toBe(true);};
 const order=(await saved()).room_objective.sequence;await visit(order[1]);expect((await saved()).room_objective.collected).toBe(0);expect(await page.evaluate(()=>window.gateCues.includes('rune_wrong'))).toBe(true);
 await visit(order[0]);await expect(progress).toContainText('Rune gate 1/3');await page.locator('#rift-viewport').screenshot({path:'test-results/rune-gate-progress.png'});
 await page.keyboard.press('Escape');await expect(page.locator('#rift-paused-badge')).toHaveText('Paused');const before=await saved();await page.evaluate(()=>history.replaceState(null,'','/abyss/rift'));await page.reload();await expect(page.locator('#rift-start')).toBeEnabled();expect((await saved()).room_objective).toEqual(before.room_objective);await page.locator('#rift-auto').uncheck();await hook();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 await visit(order[1]);await expect(progress).toContainText('Rune gate 2/3');await visit(order[2]);await expect.poll(async()=>(await saved()).status).toBe('cleared');await expect(progress).toContainText('Rune gate 3/3 · Open');
 const result=await saved();expect(result.stats.kills).toBe(1);expect(result.drops.length).toBe(1);expect(await page.evaluate(()=>window.gateCues.filter(k=>k==='rune_gate_open').length)).toBe(1);await page.locator('#rift-viewport').screenshot({path:'test-results/rune-gate-open.png'});
 await page.locator('#rift-next').click();await expect.poll(async()=>(await saved()).room).toBe(1);await expect(progress).toContainText('Targets');
});
test('rune gate rejects invalid sequence state and fits mobile',async({page})=>{
 await page.goto('/abyss/rift?scenario=rune_gate');await expect(page.locator('#rift-start')).toBeEnabled();const data=await(await page.request.get('/api/abyss/rift')).json();
 expect(await page.evaluate(data=>{const valid=v=>{try{window.RiftProtocol.validate(v,'GET');return true;}catch(_){return false;}};const order=structuredClone(data);order.run.room_objective.sequence=[1,1,3];const flags=structuredClone(data);flags.run.room_objective.pickups[0].collected=true;const touch=structuredClone(data);touch.run.room_objective.puzzle_touch=4;const complete=structuredClone(data);complete.run.room_objective.complete=true;return [data,order,flags,touch,complete].map(valid);},data)).toEqual([true,false,false,false,false]);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
