const {test,expect}=require('@playwright/test');
test('defend both lanes with WASD, persist damage, and bank normal patrol loot',async({page})=>{
 test.setTimeout(90000);await page.goto('/abyss/rift?scenario=split-defense');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();
 const saved=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run;
 const hook=()=>page.evaluate(()=>{window.laneCues=[];const play=window.RiftAudio.play;window.RiftAudio.play=function(kind,...args){if(kind.startsWith('lane'))window.laneCues.push(kind);return play.call(this,kind,...args);};});
 await hook();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 await expect.poll(async()=>(await saved()).room_objective.lanes.every(l=>l.ward.hp<=90)).toBe(true);await expect(page.locator('#rift-room-objective-directions')).toContainText('UNDER ATTACK');
 expect(await page.evaluate(()=>window.laneCues.includes('lane_threat')&&window.laneCues.includes('lane_hurt'))).toBe(true);await page.locator('#rift-viewport').screenshot({path:'test-results/defense-pressure.png'});
 await page.keyboard.press('Escape');await expect(page.locator('#rift-paused-badge')).toHaveText('Paused');const before=await saved();await page.evaluate(()=>history.replaceState(null,'','/abyss/rift'));await page.reload();await expect(page.locator('#rift-start')).toBeEnabled();expect((await saved()).room_objective).toEqual(before.room_objective);await page.locator('#rift-auto').uncheck();await hook();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 const held=new Set();try{for(let n=0;n<500;n++){const r=await saved();if(r.status!=='fighting')break;const e=r.enemies.find(e=>e.hp>0);const dx=e.x-r.player.x,dy=e.y-r.player.y,wanted=new Set(['KeyJ']);if(Math.abs(dx)>40||dx*r.player.facing<0)wanted.add(dx>0?'KeyD':'KeyA');if(Math.abs(dy)>8)wanted.add(dy>0?'KeyS':'KeyW');for(const key of held)if(!wanted.has(key)){await page.keyboard.up(key);held.delete(key);}for(const key of wanted)if(!held.has(key)){await page.keyboard.down(key);held.add(key);}await page.waitForTimeout(60);}}finally{for(const key of held)await page.keyboard.up(key);}
 await expect.poll(async()=>(await saved()).status).toBe('cleared');const result=await saved();expect(result.stats.kills).toBe(2);expect(result.drops).toHaveLength(2);expect(result.room_objective.lanes.every(l=>l.ward.hp>0)).toBe(true);expect(await page.evaluate(()=>window.laneCues.filter(k=>k==='lanes_protected').length)).toBe(1);await expect(page.locator('#rift-room-objective-progress')).toContainText('Protected');await page.locator('#rift-viewport').screenshot({path:'test-results/defense-protected.png'});
 await page.locator('#rift-next').click();await expect.poll(async()=>(await saved()).room).toBe(1);await expect(page.locator('#rift-room-objective-help')).toContainText('spirit');
});
test('a lost lane ends the expedition without killing the shared character',async({page})=>{
 await page.goto('/abyss/rift?scenario=split-defense-failure');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();const saved=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run;const initial=await saved();await page.locator('#rift-start').click();await expect.poll(async()=>(await saved()).status).toBe('defeated');await expect(page.locator('#rift-overlay-title')).toHaveText('A lane ward fell.');const result=await saved();expect(result.player.hp).toBe(initial.player.hp);expect(result.gold).toBe(0);expect(result.drops).toHaveLength(0);expect(result.room_objective.lanes[1].ward.hp).toBe(0);await page.locator('#rift-viewport').screenshot({path:'test-results/defense-lost.png'});
});
test('defense protocol rejects invalid ward or assignment state and mobile HUD fits',async({page})=>{
 await page.goto('/abyss/rift?scenario=split-defense');await expect(page.locator('#rift-start')).toBeEnabled();const data=await(await page.request.get('/api/abyss/rift')).json();expect(await page.evaluate(data=>{const valid=v=>{try{window.RiftProtocol.validate(v,'GET');return true;}catch(_){return false;}};const changed=fn=>{const v=structuredClone(data);fn(v.run.room_objective);return v;};return [data,changed(o=>o.lanes[0].ward.hp=101),changed(o=>o.lanes[1].enemy_ids.push(o.lanes[0].enemy_ids[0])),changed(o=>o.lanes[0].seconds=1),changed(o=>o.complete=true)].map(valid);},data)).toEqual([true,false,false,false,false]);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
