const {test,expect}=require('@playwright/test');
test('loot shows original description and honest class primary-stat guidance',async({page})=>{
 await page.goto('/abyss/rift?scenario=checkpoint&subclass=geomancer');await expect(page.locator('#rift-start')).toBeEnabled();const saved=(await(await page.request.get('/api/abyss/rift')).json()).run;expect(saved.build.class_scaling).toBe('DEF');
 const show=async(value,primary='DEF',description='Original <Abyss> lore')=>page.evaluate(({saved,value,primary,description})=>{const run=structuredClone(saved);run.build.class_scaling=primary;run.drops=[{id:'test',x:100,y:400,gold:0,collected:true,banked:false,gear_description:description,gear:{ID:'test',Name:'Test drop',Slot:'Chest',Rarity:1,Stats:{DEF:value},MaxDurability:100}}];RiftLoot.update(run,true);},{saved,value,primary,description});
 await show(12);await page.locator('#rift-loot > li > details > summary').click();await expect(page.locator('.rift-gear-description')).toHaveText('Original <Abyss> lore');await expect(page.locator('.rift-gear-description abyss')).toHaveCount(0);await expect(page.locator('.rift-gear-class-fit')).toContainText('+12 DEF');await expect(page.locator('.rift-gear-class-fit')).toContainText('not class-restricted');
 await show(-5);await expect(page.locator('.rift-gear-class-fit')).toContainText('Reduces DEF by 5');await show(0);await expect(page.locator('.rift-gear-class-fit')).toContainText('Other stats and effects may still help');await show(0,'','');await expect(page.locator('.rift-gear-class-fit')).toContainText('unavailable');await expect(page.locator('.rift-gear-description')).toContainText('No original Abyss description');
 await show(12);await page.locator('#rift-loot > li > details > summary').click();await page.setViewportSize({width:390,height:1600});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#rift-loot').scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollBy(0,-240));await page.locator('#rift-loot').screenshot({path:'test-results/gear-guidance-mobile.png'});
 expect((await(await page.request.get('/api/abyss/rift')).json()).run).toEqual(saved);
});
