const {test,expect}=require('@playwright/test');
test('local practice best is configuration-specific, persistent and independently resettable',async({page})=>{
 await page.goto('/abyss/rift?practice=movement');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();await page.keyboard.down('d');const read=async()=>(await(await page.request.get('/api/abyss/rift?practice=movement')).json()).run;await expect.poll(async()=>(await read()).practice.completed,{timeout:15000}).toBe(true);await page.keyboard.up('d');const completed=await read(),best=page.locator('#rift-practice-best');await expect(best).toContainText('Best:');const initial=await best.textContent();
 await page.reload();await expect(best).toHaveText(initial);await page.evaluate(run=>{run.stats.seconds+=5;run.last_ms++;RiftRecords.update(run);},completed);await expect(best).toHaveText(initial);
 await page.evaluate(run=>{run.build.hp++;RiftRecords.update({...run,status:'fighting',practice:{...run.practice,completed:false}});},completed);await expect(best).toContainText('No completed');await page.evaluate(run=>RiftRecords.update(run),completed);await expect(best).toHaveText(initial);
 await page.setViewportSize({width:390,height:1600});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#rift-local-practice-record').scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollBy(0,-240));await page.locator('#rift-local-practice-record').screenshot({path:'test-results/local-practice-record-mobile.png'});
 await page.locator('#rift-reset-practice-records').click();await expect(best).toContainText('No completed');expect(await read()).toEqual(completed);await page.reload();await expect(best).toContainText('No completed');
 await page.goto('/abyss/rift?practice=skills');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-start').click();await expect(best).toContainText('Open-ended');
});
