const {test,expect}=require('@playwright/test');

test('optional combat text preference persists and preserves damage and hazard warnings',async({page})=>{
 await page.goto('/abyss/rift');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('.rift-settings > summary').click();const option=page.locator('#rift-optional-combat-text');await expect(option).toBeChecked();await option.uncheck();await page.reload();await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('.rift-settings > summary').click();await expect(option).not.toBeChecked();await page.locator('.rift-settings > summary').click();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();await page.keyboard.press('Escape');await expect(page.locator('#rift-paused-badge')).toHaveText('Paused');
 const run=(await(await page.request.get('/api/abyss/rift')).json()).run;
 await page.evaluate(async run=>{run.paused=false;run.clock=0;run.enemies=[];run.projectiles=[];run.drops=[{x:400,y:400,gear:{Slot:'weapon',Rarity:0}}];run.level.rooms[0].hazards=[{kind:'fire',x:300,y:300,w:80,h:50,offset:0,period:5,duration:2}];const id=run.counter;run.counter+=2;run.events=[{id:id+1,kind:'pickup',value:91,x:400,y:200},{id:id+2,kind:'hurt',value:37,x:400,y:220}];const ctx=document.getElementById('rift-canvas').getContext('2d');window.labels=[];const original=ctx.fillText.bind(ctx);ctx.fillText=(text,...args)=>{window.labels.push(text);return original(text,...args);};await window.RiftRenderer.prepareRun(run);window.RiftRenderer.snapshot(run,false);},run);
 await expect.poll(()=>page.evaluate(()=>window.labels.includes('37'))).toBe(true);expect(await page.evaluate(()=>window.labels.includes('+91 gold'))).toBe(false);expect(await page.evaluate(()=>window.labels.includes('ABYSS GEAR'))).toBe(false);expect(await page.evaluate(()=>window.labels.some(label=>/^FIRE IN /.test(label)))).toBe(true);
 await page.locator('.rift-settings > summary').click();await page.locator('#rift-reset-display').click();await expect(option).toBeChecked();await page.evaluate(async run=>{run.paused=false;run.drops=[{x:400,y:400,gear:{Slot:'weapon',Rarity:0}}];run.counter+=4;run.events=[{id:run.counter,kind:'pickup',value:91,x:400,y:200}];await window.RiftRenderer.prepareRun(run);window.RiftRenderer.snapshot(run,false);},run);await expect.poll(()=>page.evaluate(()=>window.labels.includes('+91 gold'))).toBe(true);await expect.poll(()=>page.evaluate(()=>window.labels.includes('ABYSS GEAR'))).toBe(true);expect((await(await page.request.get('/api/abyss/rift')).json()).run.paused).toBe(true);
});
