const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
for(const reduced of [false,true])test('hazard warning stays above large boss on bright ice, reduced='+reduced,async({page})=>{
 await page.emulateMedia({reducedMotion:reduced?'reduce':'no-preference'});await page.goto('/abyss/rift?scenario=checkpoint');await expect(page.locator('#rift-start')).toBeEnabled();const {run}=await(await page.request.get('/api/abyss/rift')).json();
 await page.evaluate(()=>{window.hazardDraws=[];for(const method of ['drawImage','strokeRect','fillRect','fillText']){const orig=CanvasRenderingContext2D.prototype[method];CanvasRenderingContext2D.prototype[method]=function(...args){if(this.canvas.id==='rift-canvas'){const frame=RiftRenderer.frameCount;if(hazardDraws[0]?.frame!==frame)hazardDraws=[];hazardDraws.push({frame,method,args:method==='drawImage'?[]:args,fill:this.fillStyle,dash:this.getLineDash()});}return orig.apply(this,args);};}});
 const show=(clock,labels=true,clean=false)=>page.evaluate(({run,clock,labels,clean})=>{run.paused=true;run.status='fighting';run.clock=clock;run.player.x=160;run.level.region=2;run.events=[];run.drops=[];run.enemies=[{id:'occluding-boss',kind:'boss',x:460,y:410,hp:100,max_hp:100,facing:-1,pose:'idle'}];run.level.rooms[run.room].hazards=[{x:400,y:380,w:120,h:32,kind:'ice',jumpable:true,period:7,offset:0,duration:1}];RiftDisplay.hazardLabels=labels;RiftDisplay.cleanScreenshot=clean;hazardDraws=[];RiftRenderer.snapshot(run,true);},{run,clock,labels,clean});
 for(const [clock,label,dashed] of [[0,'ICE IN 1.2s',true],[1.3,'JUMP · 0.9s',false]]){
  await show(clock);await expect.poll(()=>page.evaluate(({label,dashed})=>{const a=hazardDraws,lastImage=a.findLastIndex(v=>v.method==='drawImage'),text=a.findIndex(v=>v.method==='fillText'&&v.args[0]===label),rim=a.findLastIndex(v=>v.method==='strokeRect'&&v.args[2]===120&&v.args[3]===32),plate=a.findLastIndex(v=>v.method==='fillRect'&&v.fill==='#071b16');return text>lastImage&&rim>lastImage&&plate>lastImage&&plate<text&&(a[rim].dash.length>0)===dashed;},{label,dashed})).toBe(true);
 }
 const png=await page.locator('#rift-canvas').evaluate(c=>c.toDataURL('image/png'));fs.writeFileSync('test-results/hazard-visibility'+(reduced?'-reduced':'')+'.png',Buffer.from(png.split(',')[1],'base64'));
 for(const [labels,clean] of [[false,false],[true,true]]){await show(0,labels,clean);await page.waitForTimeout(150);expect(await page.evaluate(()=>hazardDraws.some(v=>v.method==='fillText'&&String(v.args[0]).startsWith('ICE IN')))).toBe(false);}
});
