const {test,expect}=require('@playwright/test');
test('optional class track uses saved counters, survives reload and resets for new expeditions',async({page})=>{
 await page.goto('/abyss/rift?scenario=spawn-hazards&subclass=marksman');await expect(page.locator('#rift-start')).toBeEnabled();const {run}=await(await page.request.get('/api/abyss/rift')).json(),body=page.locator('#rift-class-challenges-body'),summary=page.locator('#rift-class-challenges-summary');await expect(body).toBeHidden();await page.locator('#rift-class-challenges > summary').click();await page.locator('#rift-class-challenges-enabled').check();await expect(summary).toContainText('Ranger · Marksman');await expect(summary).toContainText('0/4');
 await page.evaluate(run=>{run.stats.charged_finishers=1;run.stats.charges_spent=3;run.stats.rooms_cleared=1;RiftClassChallenges.update(run);},run);await expect(summary).toContainText('1/4');await expect(body).toContainText(run.build.signatures.find(s=>s.role==='finisher').name);
 await page.evaluate(run=>{run.stats.charged_finishers=10;run.stats.charges_spent=20;run.stats.rooms_cleared=3;RiftClassChallenges.update(run);},run);await expect(summary).toContainText('Track complete!');await expect(page.locator('#rift-class-challenges-list [data-complete="true"]')).toHaveCount(4);
 await page.setViewportSize({width:390,height:1600});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#rift-class-challenges').scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollBy(0,-240));await page.locator('#rift-class-challenges').screenshot({path:'test-results/class-challenges-mobile.png'});
 await page.evaluate(run=>{run.id='new-expedition';run.stats={charged_finishers:0,charges_spent:0,rooms_cleared:0};RiftClassChallenges.update(run);},run);await expect(summary).toContainText('0/4');
 expect((await(await page.request.get('/api/abyss/rift')).json()).run).toEqual(run);await page.evaluate(()=>history.replaceState(null,'','/abyss/rift'));await page.reload();await page.locator('#rift-class-challenges > summary').click();await expect(page.locator('#rift-class-challenges-enabled')).toBeChecked();await expect(body).toBeVisible();await expect(summary).toContainText('0/4');
 await page.evaluate(run=>{run.stats={};RiftClassChallenges.update(run);},run);await expect(body).toContainText('Progress unavailable');await expect(page.locator('#rift-class-challenges-list progress')).toHaveCount(0);
 await page.evaluate(run=>{run.build.signatures=[];RiftClassChallenges.update(run);},run);await expect(summary).toContainText('need your equipped builder and finisher');
 await page.evaluate(run=>{run.practice={mode:'class'};RiftClassChallenges.update(run);},run);await expect(page.locator('#rift-class-challenges')).toBeHidden();
});

test('a real charged finisher advances the optional class track',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('riftClassChallenges','true'));await page.goto('/abyss/rift?scenario=spawn-hazards&subclass=marksman');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 const read=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run;await page.keyboard.press('q');await expect.poll(async()=>(await read()).resource).toBe(1);await expect.poll(async()=>(await read()).player.cooldown).toBe(0);await page.keyboard.press('e');await expect.poll(async()=>(await read()).stats.charged_finishers).toBe(1);await expect(page.locator('#rift-class-challenges-summary')).toContainText('1/4');expect((await read()).stats.charges_spent).toBe(1);
});
