const {test,expect}=require('@playwright/test');
test('wood takes damage, survives reload, breaks and leaves loot reachable',async({page})=>{
 test.setTimeout(90000);await page.goto('/abyss/rift?scenario=terrain-cover');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();const saved=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run;
 await page.evaluate(()=>{window.coverCues=[];const play=window.RiftAudio.play;window.RiftAudio.play=function(kind,...args){if(kind.startsWith('cover_'))window.coverCues.push(kind);return play.call(this,kind,...args);};});
 await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 await page.keyboard.down('KeyD');try{await expect.poll(async()=>(await saved()).player.x,{intervals:[20]}).toBeGreaterThan(240);}finally{await page.keyboard.up('KeyD');}
 await page.locator('#rift-viewport').screenshot({path:'test-results/cover-intact.png'});
 await page.keyboard.press('KeyJ');await expect.poll(async()=>(await saved()).level.rooms[0].cover[0].hp).toBeLessThan(60);expect((await saved()).level.rooms[0].cover[0].hp).toBeGreaterThan(0);expect(await page.evaluate(()=>window.coverCues.includes('cover_hit'))).toBe(true);
 await page.locator('#rift-viewport').screenshot({path:'test-results/cover-damaged.png'});await page.keyboard.press('Escape');await expect(page.locator('#rift-paused-badge')).toHaveText('Paused');const before=await saved();await page.evaluate(()=>history.replaceState(null,'','/abyss/rift'));await page.reload();await expect(page.locator('#rift-start')).toBeEnabled();expect((await saved()).level.rooms[0].cover).toEqual(before.level.rooms[0].cover);await page.locator('#rift-auto').uncheck();await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 await page.keyboard.down('KeyJ');try{await expect.poll(async()=>(await saved()).level.rooms[0].cover[0].hp).toBe(0);}finally{await page.keyboard.up('KeyJ');}
 await page.keyboard.down('KeyD');try{await expect.poll(async()=>(await saved()).player.x,{intervals:[20]}).toBeGreaterThan(420);}finally{await page.keyboard.up('KeyD');}
 expect((await saved()).drops.find(d=>d.id==='behind-wood').collected).toBe(true);expect((await saved()).stats.kills).toBe(0);await page.locator('#rift-viewport').screenshot({path:'test-results/cover-broken.png'});
 await page.keyboard.down('KeyD');try{await expect.poll(async()=>(await saved()).player.x,{intervals:[20]}).toBeGreaterThan(590);}finally{await page.keyboard.up('KeyD');}
 await page.keyboard.down('KeyD');await page.keyboard.down('Space');await page.keyboard.down('KeyJ');await page.waitForTimeout(1400);await page.keyboard.up('KeyD');await page.keyboard.up('Space');await page.keyboard.up('KeyJ');const stone=await saved();expect(stone.player.x).toBeLessThan(650);expect(stone.level.rooms[0].cover[1]).toMatchObject({material:'stone',hp:0,max_hp:0});await page.locator('#rift-viewport').screenshot({path:'test-results/cover-stone.png'});
});
test('cover protocol rejects invalid materials, durability and duplicate IDs',async({page})=>{
 await page.goto('/abyss/rift?scenario=terrain-cover');await expect(page.locator('#rift-start')).toBeEnabled();const data=await(await page.request.get('/api/abyss/rift')).json();expect(await page.evaluate(data=>{const valid=v=>{try{window.RiftProtocol.validate(v,'GET');return true;}catch(_){return false;}};const changed=fn=>{const v=structuredClone(data);fn(v.run.level.rooms[0].cover);return v;};return [data,changed(c=>c[0].hp=61),changed(c=>c[0].material='glass'),changed(c=>c[1].id=c[0].id),changed(c=>c[1].hp=1)].map(valid);},data)).toEqual([true,false,false,false,false]);
});

for(const scenario of ['terrain-projectile','terrain-stone-projectile'])test(scenario+' stops at the first cover impact',async({page})=>{
 await page.goto('/abyss/rift?scenario='+scenario);await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();const saved=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run;const initial=await saved();
 await page.evaluate(()=>{window.impactCues=[];window.impactOscillators=0;let nodes=0;const create=BaseAudioContext.prototype.createOscillator;BaseAudioContext.prototype.createOscillator=function(...args){nodes++;return create.apply(this,args);};const play=window.RiftAudio.play;window.RiftAudio.play=function(kind,...args){if(['projectile_impact','cover_break'].includes(kind))window.impactCues.push(kind);const before=nodes,result=play.call(this,kind,...args);if(kind==='projectile_impact')window.impactOscillators+=nodes-before;return result;};});
 await page.locator('#rift-start').click();await expect.poll(async()=>(await saved()).projectiles.length).toBe(0);const result=await saved();expect(result.player.hp).toBe(initial.player.hp);expect(result.stats.kills).toBe(0);expect(result.level.rooms[0].cover[0].hp).toBe(scenario==='terrain-projectile'?0:60);expect(await page.evaluate(()=>window.impactCues.includes('projectile_impact'))).toBe(true);expect(await page.evaluate(()=>window.impactOscillators)).toBeGreaterThan(0);if(scenario==='terrain-projectile')expect(await page.evaluate(()=>window.impactCues.includes('cover_break'))).toBe(true);
});
test('campaign route previews identify wooden and stone cover',async({page})=>{
 await page.goto('/abyss/rift?mission=4');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-mission-preview > summary').click();await expect(page.locator('#rift-room-previews [data-terrain="wood"]')).toHaveCount(1);await expect(page.locator('#rift-room-previews [data-terrain="wood"] title')).toHaveText('Breakable wood: 60 / 60');await page.locator('[data-level="2"]').click();await expect(page.locator('#rift-room-previews [data-terrain="stone"]')).toHaveCount(1);await expect(page.locator('#rift-room-previews [data-terrain="stone"] title')).toContainText('blocks movement and projectiles');
});
