const {test,expect}=require('@playwright/test');
test('class records and resource messages use supplied Abyss terminology',async({page})=>{
 await page.goto('/abyss/rift?scenario=spawn-hazards&subclass=alchemist');await expect(page.locator('#rift-start')).toBeEnabled();const data=await(await page.request.get('/api/abyss/rift')).json();expect(Object.keys(data.class_names)).toHaveLength(18);expect(data.class_names.alchemist).toBe(data.build.class_name);expect(await page.evaluate(data=>{try{RiftProtocol.validate({...data,class_names:{alchemist:42}},'GET');return false;}catch(_){return true;}},data)).toBe(true);
 await page.evaluate(data=>{
  RiftRecords.init({...data.class_names,alchemist:'Abyss Apothecary'});const run=data.run;run.build.resource='Test Essence';run.resource=1;run.mission_history=Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,{completed_by_class:{alchemist:1}}]));run.attempt_history=[{mission:1,outcome:'completed',class:'alchemist',at_ms:0,seconds:1,hp:1,max_hp:1}];RiftRecords.update(run);RiftCampaignTools.update(run,1);RiftHUD.update(run,false);
 },data);
 await expect(page.locator('#rift-class-mastery-list')).toContainText('Abyss Apothecary (current)');await expect(page.locator('#rift-attempt-list')).toContainText('Abyss Apothecary');await expect(page.locator('#rift-class-badges')).toContainText('Abyss Apothecary mastery');await expect(page.locator('#rift-alchemist-sequence')).toContainText('Test Essence 1/3');await expect(page.locator('#rift-low-resource')).toContainText('Spending Test Essence charges');
 await page.evaluate(data=>{RiftRecords.init({...data.class_names,alchemist:'Renamed Alchemist'});const run=data.run;run.mission_history=Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,{completed_by_class:{alchemist:1}}]));RiftCampaignTools.update(run,1);RiftRecords.update(run);},data);await expect(page.locator('#rift-class-badges')).toContainText('Renamed Alchemist mastery');await expect(page.locator('#rift-class-mastery-list')).toContainText('Renamed Alchemist');
 await page.evaluate(data=>{const run=data.run;run.paused=false;run.resource=0;run.build.resource='Test Essence';RiftHUD.update(run,true);run.resource=2;RiftHUD.update(run,true);},data);await expect(page.locator('#rift-resource-gain')).toHaveText('+2 Test Essence');
 expect((await(await page.request.get('/api/abyss/rift')).json()).run).toEqual(data.run);
});
