const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
for(const reduced of [false,true])test((reduced?'reduced motion: ':'')+'walk onto and off a raised platform with aligned shadow and saved height',async({page})=>{
 await page.emulateMedia({reducedMotion:reduced?'reduce':'no-preference'});
 await page.addInitScript(()=>{const ellipse=CanvasRenderingContext2D.prototype.ellipse;CanvasRenderingContext2D.prototype.ellipse=function(x,y,rx,ry,...args){if(Math.abs(rx-28.28)<.01&&Math.abs(ry-7)<.01)window.platformShadowY=y;return ellipse.call(this,x,y,rx,ry,...args);};});
 await page.goto('/abyss/rift?scenario=raised-platform');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-auto').uncheck();await page.evaluate(()=>{window.platformSteps=[];const step=RiftAudio.step;RiftAudio.step=function(floor,...args){platformSteps.push(floor);return step.call(this,floor,...args);};});await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();const saved=async()=>(await(await page.request.get('/api/abyss/rift')).json()).run;
 await page.keyboard.down('KeyD');try{await expect.poll(async()=>(await saved()).player.x,{intervals:[20]}).toBeGreaterThan(250);}finally{await page.keyboard.up('KeyD');}
 await page.keyboard.press('Escape');await expect(page.locator('#rift-paused-badge')).toHaveText('Paused');let run=await saved();expect(run.player.elevation).toBe(16);expect(run.floor).toBe('stone');expect(await page.evaluate(()=>platformSteps.includes('stone'))).toBe(true);expect(run.stats.jumps||0).toBe(0);await expect.poll(()=>page.evaluate(()=>window.platformShadowY)).toBe(396);
 const data=await page.locator('#rift-canvas').evaluate(c=>c.toDataURL('image/png'));fs.writeFileSync('test-results/raised-platform'+(reduced?'-reduced':'')+'.png',Buffer.from(data.split(',')[1],'base64'));
 await expect(page.locator('#rift-minimap [data-kind=platform]')).toHaveCount(1);await page.evaluate(()=>history.replaceState(null,'','/abyss/rift'));await page.reload();await expect(page.locator('#rift-start')).toBeEnabled();expect((await saved()).player.elevation).toBe(16);await page.locator('#rift-start').click();await expect(page.locator('#rift-overlay')).toBeHidden();
 await page.keyboard.down('KeyD');try{await expect.poll(async()=>(await saved()).player.x,{intervals:[20]}).toBeGreaterThan(375);}finally{await page.keyboard.up('KeyD');}
 run=await saved();expect(run.player.elevation||0).toBe(0);expect(run.floor).toBe('grass');expect(run.stats.jumps||0).toBe(0);expect(run.player.hp).toBe(run.player.max_hp);
});
test('platform protocol rejects invalid ramps and heights and preview shows raised terrain',async({page})=>{
 await page.goto('/abyss/rift?scenario=raised-platform');await expect(page.locator('#rift-start')).toBeEnabled();const data=await(await page.request.get('/api/abyss/rift')).json();expect(await page.evaluate(data=>{const valid=v=>{try{RiftProtocol.validate(v,'GET');return true;}catch(_){return false;}};const change=fn=>{const v=structuredClone(data);fn(v);return v;};return [data,change(v=>v.run.level.rooms[0].platforms[0].rise=40),change(v=>v.run.level.rooms[0].platforms[0].ramp=60),change(v=>v.run.level.rooms[0].platforms[0].ramp=5),change(v=>v.run.player.elevation=-1)].map(valid);},data)).toEqual([true,false,false,false,false]);
 await page.goto('/abyss/rift?mission=2');await expect(page.locator('#rift-start')).toBeEnabled();await page.locator('#rift-mission-preview > summary').click();await expect(page.locator('#rift-room-previews [data-terrain=platform]')).toHaveCount(1);
});

test('projectiles loot and hit effects render at their saved surface height',async({page})=>{
 await page.goto('/abyss/rift?scenario=raised-platform');await expect(page.locator('#rift-start')).toBeEnabled();const run=(await(await page.request.get('/api/abyss/rift')).json()).run;
 await page.evaluate(run=>{window.heightDraws={};const ctx=document.getElementById('rift-canvas').getContext('2d'),translate=ctx.translate,draw=ctx.drawImage;ctx.translate=function(x,y){if(Math.abs(x-550)<.01)heightDraws.projectile=y;return translate.call(this,x,y);};ctx.drawImage=function(img,...args){if(args.length===8){if(img.src?.includes('rift_items'))heightDraws.loot=args[5]+args[7]/2;if(img.src?.includes('rift_effects')&&args[6]===95)heightDraws.hit=args[5]+args[7]/2;}return draw.call(this,img,...args);};RiftDisplay.cleanScreenshot=true;RiftDisplay.lootMotion=false;RiftDisplay.lootSparkle=false;RiftRenderer.reduced=false;run.enemies=[];run.level.rooms[0].hazards=[];run.projectiles=[{x:550,y:410,vx:300,vy:0,kind:'arrow',elevation:16}];run.drops=[{id:'elevated-gold',x:430,y:410,gold:20,elevation:16}];run.counter+=100;run.events=[{id:run.counter,kind:'hit',x:700,y:380,value:1,elevation:16}];RiftRenderer.snapshot(run,false);},run);
 await expect.poll(()=>page.evaluate(()=>heightDraws.projectile)).toBe(364);await expect.poll(()=>page.evaluate(()=>heightDraws.loot)).toBe(386);await expect.poll(()=>page.evaluate(()=>heightDraws.hit)).toBeCloseTo(364.5,0);
});
