// Package content provides the flavour text the bot mixes into its messages:
// random greetings, gaming trivia, holiday theming and game-based nicknames.
// Everything here is deterministic-free (uses math/rand) and side-effect free so
// it is trivially unit-testable.
package content

import "math/rand"

// greetings holds 100 short, punchy opening lines for the poke / private message.
var greetings = []string{
	"Hey gamer!",
	"Loot drop incoming!",
	"Incoming!",
	"Free game alert!",
	"Stop scrolling, grab this!",
	"Your backlog called.",
	"Wallet stays full today!",
	"Freebie unlocked!",
	"Achievement unlocked: free game!",
	"Press F to claim!",
	"GG, here's a free one.",
	"New loot just dropped!",
	"Surprise! It's free.",
	"Zero euros, all fun.",
	"Claim it before it's gone!",
	"Another one for the library!",
	"Today's free find:",
	"Gamer, assemble!",
	"Heads up, free game!",
	"Limited time loot!",
	"Don't sleep on this one!",
	"Hot off the press:",
	"Free as in beer!",
	"Add to cart: 0,00 €",
	"Treat yourself, it's free.",
	"Pew pew, free game!",
	"Insert coin? No need.",
	"Your daily dose of free:",
	"Snag it while it lasts!",
	"Loot goblin says hi!",
	"Respawn your backlog!",
	"Free game, no catch!",
	"Tap to claim your loot!",
	"This one's on the house!",
	"Quest reward: a free game!",
	"Boom! Free game.",
	"Time to level up your library!",
	"A wild freebie appeared!",
	"Catch 'em all... for free!",
	"Critical hit: free game!",
	"No microtransactions here, just free!",
	"Free pixels for you!",
	"Sound the loot horn!",
	"One free game coming up!",
	"Stash this in your library!",
	"Cha-ching... just kidding, it's free!",
	"Power up with a free game!",
	"Free DLC for your day:",
	"Loot crate opened!",
	"Greetings, adventurer!",
	"Rise and grind, here's a freebie!",
	"Easy claim, big win!",
	"Today's drop:",
	"Yoink this free game!",
	"Free game, fresh off the rack!",
	"Mana refilled, here's a freebie!",
	"For the hoard!",
	"Stack the backlog!",
	"Don't be a noob, claim this!",
	"Speedrun to the claim button!",
	"Free game, courtesy of MrFree!",
	"Buffs incoming: free game!",
	"Loot drop of the day!",
	"Your inventory has space, right?",
	"Game on, for free!",
	"No grind, just claim!",
	"Free game, hot and ready!",
	"Special delivery, gamer!",
	"Unlock this freebie!",
	"Roll for loot... you won!",
	"It's dangerous to go alone, take this!",
	"Free game spotted in the wild!",
	"Pick it up, it's free real estate!",
	"Daily loot has arrived!",
	"Free game, zero cooldown!",
	"Claim now, thank me later!",
	"A gift from the gaming gods:",
	"Press start on this freebie!",
	"Your luck stat is high today!",
	"Free game, no strings attached!",
	"Drop everything, free game!",
	"Stonks! Free game edition.",
	"Loot incoming, brace yourself!",
	"Open your library, here's loot!",
	"Free game, freshly spawned!",
	"Hop in, the loot's free!",
	"Big W for your wallet!",
	"This freebie has your name on it!",
	"Healing potion for your backlog:",
	"Free game, certified epic!",
	"Grab it, it's giveaway o'clock!",
	"New entry for the collection!",
	"Free game, straight to inventory!",
	"Treasure found!",
	"Gamer alert: free loot!",
	"Claim this before the timer ends!",
	"Your free game has arrived!",
	"Loot secured? Almost, claim it!",
	"Free game, no cap!",
	"Here's a freebie, you legend!",
}

// RandomGreeting returns one of the 100 greetings at random.
func RandomGreeting() string {
	return greetings[rand.Intn(len(greetings))]
}

// GreetingCount is exposed for tests.
func GreetingCount() int { return len(greetings) }
