(function(global){
  'use strict';
  var W=global.ShopWorkbench,M=W.model,panel=document.getElementById('abyssTokenShop'),program=panel&&panel.querySelector('.ab-shop-program');if(!panel||!program)return;
  var wallet={gold:M.integer(program.dataset.gold),tokens:M.integer(program.dataset.tokens)},punches=M.integer(program.dataset.loyalty),pending=false,locked=false,category='supplies',offers=[],index=new Map();
  var host=W.el('div');panel.querySelector('.ab-shop-tabs').before(host);
  var work=W.create({prefix:'as',id:'abyssShopWorkbench',user:panel.dataset.shopUser||'local',host:host,surface:panel,tokens:true,wallet:function(){return wallet;},changed:function(){filter();},capture:function(){return {category:category};},restore:function(values){if(['supplies','insanity'].includes(values.category))setCategory(values.category);},locate:function(o){if(!o)return;work.resetFilters();setCategory(o.node.dataset.shopCategory);controls.Search.value=o.name;filter();o.node.scrollIntoView({block:'center'});o.node.querySelector('[data-shop-buy]').focus();}});
  var controls={};function add(id,label,type,choices){return controls[id]=work.input(id,label,type,choices);}
  add('Search','Search Abyss offers','search');add('Currency','Currency','select',[['','All currencies'],['tokens','Tokens'],['gold','Gold']]);
  add('Purpose','Purpose','select',[['','All purposes'],['heal','Healing'],['repair','Repairs'],['revive','Revival'],['boost','Combat boosts'],['random','Random rewards'],['cosmetic','Cosmetics']]);
  add('Sort','Sort offers','select',[['','Catalog order'],['name','Name'],['price','Price within currency'],['saving','Largest token saving']]);add('Affordable','Affordable now','checkbox');add('Deals','Daily deals only','checkbox');add('Cool','Cooling market only','checkbox');add('WishlistOnly','Watchlist only','checkbox');add('PlanOnly','Planned offers only','checkbox');
  var count=W.el('p');count.id='asResultCount';count.setAttribute('role','status');work.filters.appendChild(count);work.filters.appendChild(W.button('Reset Abyss filters',function(){work.resetFilters();}));
  var prep=W.section(work.body,'Prepare for a run');prep.appendChild(W.el('p','Add supplies to a plan, then review the individual purchases below. Temporary elixirs last three fights; random caches have an unknown final item. Permanent cosmetics grant no combat power.'));
  var kits={Healing:['great_potions','elixir_of_life'],Repairs:['repair_kits'],Revival:['phoenix','pet_revival_scroll'],Boosts:['giant_strength','speed_elixir_pack','lucky_draught_pack']};
  Object.keys(kits).forEach(function(name){prep.appendChild(W.button('Plan '+name.toLowerCase(),function(){kits[name].forEach(function(k){var o=index.get(k);if(o)work.addPlan(o);});}));});
  prep.appendChild(W.el('small','Plans use posted prices. A loyalty reward applies to one eligible purchase at checkout.'));
  var status=W.el('p',null,'sw-abyss-status');status.id='asStatus';status.setAttribute('role','status');status.setAttribute('aria-live','polite');host.after(status);
  var verify=W.button('Refresh to verify purchase',function(){location.reload();});verify.id='asVerify';verify.hidden=true;status.after(verify);
  function purpose(key){return /insanity_/.test(key)?'cosmetic':/repair/.test(key)?'repair':/phoenix|reviv/.test(key)?'revive':/potions|elixir_of_life/.test(key)?'heal':/gear|relic/.test(key)?'random':'boost';}
  function readOffer(row){var gold=M.integer(row.dataset.goldCost),owned=row.dataset.owned==='true';return {key:row.dataset.shopKey,name:row.dataset.shopName,price:owned?0:gold||M.integer(row.dataset.tokenCost),currency:gold?'gold':'tokens',base:M.integer(row.dataset.baseCost),slot:purpose(row.dataset.shopKey),purpose:purpose(row.dataset.shopKey),item:{},node:row,owned:owned};}
  function nextFree(){return punches===9;}
  function charged(o){return o.owned?0:o.currency==='tokens'&&nextFree()?0:o.price;}
  function annotate(o){var row=o.node,note=row.querySelector('.sw-offer-status');if(!note){note=W.el('p',null,'sw-offer-status sw-annotation');row.appendChild(note);}var pack=M.integer((o.name.match(/×\s*(\d+)/)||[])[1],1),market=M.demand(o.base,o.price),price=charged(o),remaining=wallet[o.currency]-price;
    var text=o.owned?'Owned cosmetic · equip free.':price===0&&o.currency==='tokens'?'Next loyalty purchase: free.':W.fmt(o.price)+' '+o.currency+' total'+(pack>1?' · '+W.fmt(o.price)+' ÷ '+pack+' = '+(o.price%pack?'≈':'')+W.fmt(o.price/pack)+' per item':'')+'.';
    if(!o.owned&&o.currency==='tokens'&&market.saving)text+=' Saves '+W.fmt(market.saving)+' tokens versus base.';if(!o.owned&&o.currency==='tokens'&&market.premium)text+=' '+W.fmt(market.premium)+' tokens above base.';
    text+=remaining>=0?' Wallet after: '+W.fmt(remaining)+' '+o.currency+'.':' Need '+W.fmt(-remaining)+' more '+o.currency+'.';
    text+=o.purpose==='random'?' Random reward; exact outcome unknown.':o.purpose==='cosmetic'?' Cosmetic only; no combat stats.':o.purpose==='boost'?' Temporary run preparation.':' Guaranteed listed supplies.';
    note.textContent=text;row.classList.add('sw-abyss-row');var buy=row.querySelector('[data-shop-buy]');buy.disabled=pending||locked||remaining<0;buy.setAttribute('aria-label',(o.owned?'Equip ':'Buy ')+o.name+' for '+W.fmt(price)+' '+o.currency);}
  function filter(){if(!offers.length)return;var filtered=0;offers.slice().sort(function(a,b){if(controls.Sort.value==='name')return a.name.localeCompare(b.name);if(controls.Sort.value==='price')return a.currency.localeCompare(b.currency)||a.price-b.price;if(controls.Sort.value==='saving')return M.demand(b.base,b.price).saving-M.demand(a.base,a.price).saving;return Number(a.node.dataset.order)-Number(b.node.dataset.order);}).forEach(function(o){var row=o.node,match=row.dataset.shopCategory===category&&M.search(o.name+' '+row.dataset.shopDescription,controls.Search.value)&&(!controls.Currency.value||o.currency===controls.Currency.value)&&(!controls.Purpose.value||o.purpose===controls.Purpose.value)&&(!controls.Affordable.checked||charged(o)<=wallet[o.currency])&&(!controls.Deals.checked||row.dataset.deal==='true')&&(!controls.Cool.checked||Number(row.dataset.demand)<0)&&(!controls.WishlistOnly.checked||work.isWatched(o.key))&&(!controls.PlanOnly.checked||work.isPlanned(o.key));row.hidden=!match;if(match)filtered++;row.parentElement.appendChild(row);});count.textContent=filtered?filtered+' matching offers. Gold and token prices are sorted separately.':'No offers match. Reset Abyss filters or choose another category.';}
  function refresh(){offers=Array.from(panel.querySelectorAll('[data-shop-key]')).map(readOffer);index=new Map(offers.map(function(o){return [o.key,o];}));work.setOffers(offers);offers.forEach(annotate);filter();giftSummary();}
  function setCategory(value,button){category=['supplies','insanity'].includes(value)?value:'supplies';panel.querySelectorAll('[role=tab]').forEach(function(tab){var selected=button?tab===button:tab.getAttribute('onclick').includes("'"+category+"'");tab.classList.toggle('active',selected);tab.setAttribute('aria-selected',String(selected));});filter();}
  function update(data){if(!data||data.ok===false)return;if(data.gold!==undefined&&M.integer(data.gold,null)!==null){wallet.gold=data.gold;program.dataset.gold=String(data.gold);document.getElementById('shopWalletGold').textContent=W.fmt(data.gold);setGold(data.gold);}if(data.tokens!==undefined&&M.integer(data.tokens,null)!==null){wallet.tokens=data.tokens;program.dataset.tokens=String(data.tokens);document.getElementById('shopWalletTokens').textContent='🜲 '+W.fmt(data.tokens);setTokens(data.tokens);}if(data.loyalty_punches!==undefined)punches=Math.min(9,M.integer(data.loyalty_punches));program.dataset.loyalty=String(punches);document.getElementById('shopLoyaltyValue').textContent=punches+' / 10';var meter=program.querySelector('.ab-shop-loyalty i');if(meter){meter.style.setProperty('--p',punches);meter.setAttribute('role','img');meter.setAttribute('aria-label',punches+' loyalty purchases recorded');}var note=document.getElementById('shopLoyaltyNotice');note.textContent=nextFree()?'Your next eligible token catalog item, bundle or gift is free. Gold services still cost gold.':(data.loyalty_free?'Free reward redeemed. ':'')+(9-punches)+' paid token purchase'+(9-punches===1?'':'s')+' until your next purchase is free. Gold services do not consume punches.';refresh();}
  function mutationButtons(){return Array.from(document.querySelectorAll('#abyssTokenShop button[onclick],#abyssTokenExchange button[onclick],.ab-shop-gift button[type=submit],.ab-shop-gift button[onclick]')).filter(function(b){return !b.matches('[role=tab]');});}
  async function execute(url,body,button,message){
    if(pending||locked||global.busy)return {ok:false,error:locked?'Refresh to verify the last purchase.':'A shop action is already pending.'};
    pending=true;setBusy(true);var originals=mutationButtons().map(function(b){var saved={node:b,disabled:b.disabled};b.disabled=true;return saved;}),label=button&&button.textContent,timer;
    if(button){button.disabled=true;button.setAttribute('aria-busy','true');button.textContent='Processing…';}status.textContent='Processing shop action…';
    try{
      var result=await Promise.race([abRawPost(url,body||{}),new Promise(function(resolve){timer=setTimeout(function(){resolve({ok:false,unconfirmed:true,error:'The shop response timed out.'});},15000);})]);
      if(!result||typeof result.ok!=='boolean'||result.unconfirmed||result.error==='network error'||/^server error/.test(result.error||'')||result.ok&&['gold','tokens'].some(function(k){return result[k]!==undefined&&M.integer(result[k],null)===null;})){
        locked=true;verify.hidden=false;status.textContent='Purchase result is unconfirmed. Refresh to verify your wallet and rewards before another shop action.';return {ok:false,unconfirmed:true,error:status.textContent};
      }
      if(!result.ok){status.textContent=result.error||'Purchase rejected. Review the offer and try again.';return result;}
      if(result.consumables)renderConsumables(result.consumables);update(result);status.textContent=result.msg||message||'Shop action completed.';work.receipt(status.textContent);abToast(status.textContent,true);return result;
    }catch(_){locked=true;verify.hidden=false;status.textContent='Purchase result is unknown. Refresh to verify before trying again.';return {ok:false,unconfirmed:true,error:status.textContent};}
    finally{clearTimeout(timer);pending=false;setBusy(false);originals.forEach(function(saved){saved.node.disabled=locked||saved.disabled;});if(button){button.textContent=label;button.removeAttribute('aria-busy');}offers.forEach(annotate);if(locked)mutationButtons().forEach(function(b){b.disabled=true;});}
  }
  async function buy(key,quoted,button){var o=index.get(key);if(!o)return;var result=await execute('/api/abyss/shop/buy',{item:key,quoted_cost:M.integer(o.node.dataset.tokenCost)},button,'Purchased '+o.name+'.');if(!result.ok&&M.integer(result.current_cost,null)!==null){o.node.dataset.tokenCost=String(result.current_cost);button.textContent='🜲 '+W.fmt(result.current_cost);button.title='Updated posted price: '+W.fmt(result.current_cost)+' tokens. Review before trying again.';refresh();}if(result.ok&&result.owned){o.node.dataset.owned='true';button.textContent='Equip · free';refresh();}return result;}
  var recipient=document.getElementById('abyssGiftRecipient'),giftItem=document.getElementById('abyssGiftItem'),code=document.getElementById('abyssGiftCode'),giftOutput=document.getElementById('abyssGiftOutput'),giftForm=recipient&&recipient.closest('form'),giftPrice=W.el('p',null,'sw-annotation'),recipientCount=W.el('small');
  giftPrice.id='asGiftPrice';if(giftForm){giftItem.parentElement.after(giftPrice);recipient.after(recipientCount);recipient.addEventListener('input',giftSummary);giftItem.addEventListener('change',giftSummary);}
  function giftSummary(){if(!giftForm)return;var o=index.get(giftItem.value),fee=M.integer(program.dataset.giftFee);recipientCount.textContent=Math.max(0,96-recipient.value.length)+' recipient characters remaining';giftPrice.textContent=o?'Supply: '+W.fmt(nextFree()?0:o.price)+' tokens · delivery: '+W.fmt(fee)+' gold. Both resources are required.':'Select a currently available gift supply.';}
  async function createGift(event){event.preventDefault();var name=recipient.value.trim();if(!name){giftOutput.textContent='Enter the recipient nickname or UID.';recipient.focus();return;}recipient.value=name;var offer=index.get(giftItem.value);if(!offer){giftOutput.textContent='This gift supply is unavailable. Refresh the shop to review its price.';return;}var b=giftForm.querySelector('[type=submit]'),result=await execute('/api/abyss/shop/gift_create',{recipient:name,item:giftItem.value,quoted_cost:M.integer(offer.node.dataset.tokenCost)},b,'Gift created.');if(!result.ok&&M.integer(result.current_cost,null)!==null){offer.node.dataset.tokenCost=String(result.current_cost);offer.node.querySelector('[data-shop-buy]').textContent='🜲 '+W.fmt(result.current_cost);refresh();}if(result.ok&&result.code){giftOutput.replaceChildren(W.el('span','Gift code: '+result.code),W.button('Copy gift code',function(){W.copy(String(result.code),giftOutput);}));}else giftOutput.textContent=result.error||'Gift could not be created.';}
  async function redeemGift(){var value=code.value.replace(/\s+/g,'');if(!value){giftOutput.textContent='Enter a gift code.';code.focus();return;}code.value=value;var b=code.parentElement.querySelector('button'),result=await execute('/api/abyss/shop/gift_redeem',{code:value},b,'Gift redeemed.');giftOutput.textContent=result.msg||result.error||'';if(result.ok)code.value='';}
  async function season(button){var result=await execute('/api/abyss/season/exchange',{},button,'Legacy cosmetic unlocked.');if(result.ok){button.textContent='Owned';button.disabled=true;}}
  function walletChanged(currency,value){if(M.integer(value,null)===null||wallet[currency]===value)return;wallet[currency]=value;program.dataset[currency]=String(value);document.getElementById(currency==='gold'?'shopWalletGold':'shopWalletTokens').textContent=currency==='gold'?W.fmt(value):'🜲 '+W.fmt(value);refresh();}
  global.AbyssShopWorkbench={buy:buy,category:setCategory,update:update,walletChanged:walletChanged,execute:execute,giftCreate:createGift,giftRedeem:redeemGift,season:season,bundle:function(key,cost,button){return execute('/api/abyss/shop/bundle',{bundle:key,quoted_cost:cost},button,'Bundle purchased.');}};
  work.onChange(function(){offers.forEach(annotate);});update({gold:wallet.gold,tokens:wallet.tokens});
})(window);
