(function(){
 'use strict';
 const root=document.getElementById('rift-class-comparison'),left=document.getElementById('rift-compare-class-left'),right=document.getElementById('rift-compare-class-right');
 let catalog=[];
 const focus={vanguard:'Build protection, then use a charged armor-piercing finisher. Frontal perfect guards can also build charges.',berserker:'Charged finishers punish wounded targets. Low health activates passive Fury.',marksman:'Mark a target with the builder to add armor piercing to a charged finisher against that target.',beastmaster:'Equipped pets increase charged-finisher damage, capped at three pets. Aim pack shots along the target lane.',elementalist:'Hit the builder-marked target with a charged finisher to trigger extra reaction damage.',chronomancer:'Spend charges while other abilities or jump are cooling down to recover cooldown time.',oracle:'Heal yourself to build charges, even at full health, then spend them on radiant damage.',geomancer:'Build a barrier, then spend charges on a finisher with extra armor piercing.',bloodblade:'Recover health through your builder and charge spending while continuing to attack.',voidwalker:'Charged finishers spend health for damage; marking the target adds armor piercing.',runesmith:'Charge spending grants a barrier. An equipped relic also boosts charged-finisher damage.',alchemist:'Build charges and mark a target, then spend charges for healing and marked-target armor piercing.'};
 const guides={
  vanguard:['to build a charge and protect yourself.','against a nearby armored enemy after gaining a charge.','Face incoming attacks and guard while waiting for the next builder.','Perfect guard lasts 0.22 seconds after raising guard. Holding guard does not renew it; one successful frontal perfect guard per raise can add a charge.'],
  berserker:['to build a charge while attacking your target.','against a wounded target when possible.','Evade the next warning and rebuild charges; do not seek damage just to activate Fury.','The execution bonus checks target health at impact: half health or less. Passive Fury checks your health at impact, and ends when you heal above 30%.'],
  marksman:['and wait until the intended enemy shows the mark.','along the marked enemy’s lane after gaining a charge.','Mark a new living target when the old target is defeated or escapes.','Charge gain alone does not prove the builder projectile landed. Confirm the mark first; the finisher hits the first enemy in its lane, so another enemy can intercept it.'],
  beastmaster:['to mark the enemy you want the pack to attack.','while facing the target and aligned with its lane.','Evade and rebuild charges; your saved equipped pets determine the damage bonus.','Pack attacks travel in your facing direction and can hit an intervening enemy. Pet scaling is capped at three equipped pets and only affects charged finishers.'],
  elementalist:['and confirm that your intended target is marked.','on that same target after gaining a charge.','Reapply the builder mark before the next reaction attempt.','Wait for the builder hit rather than only the resource increase. A charged finisher gains the reaction bonus when it hits the target marked at cast time.'],
  chronomancer:['to gain a charge.','after using another ability or jump so its cooldown can be recovered.','Use the recovered action when ready, then build charges again.','A charged finisher removes up to 1.5 seconds from other ability and jump cooldowns. The finisher itself and environment/status timers are excluded; additional charges do not increase rewind time.'],
  oracle:['to recover health and build a charge.','as a radiant attack while facing your target.','Use the builder again when ready; it can build charges even at full health.','Healing is capped at maximum HP and overflow is discarded. A successful builder cast still gains a charge at full health unless charges are already full.'],
  geomancer:['to establish a barrier and gain a charge.','against an armored enemy when in range.','Rebuild protection while respecting mana and cooldowns.','Barrier capacity is capped at half maximum HP, so casting into a nearly full barrier can waste protection. Charged finishers add armor piercing; keep a charge for armored targets.'],
  bloodblade:['while attacking to build a charge and recover health.','when you have a charge and missing health.','Evade incoming attacks while rebuilding; recovery does not prevent a lethal hit.','Charged-finisher recovery happens on cast and is capped at full health. Each spent charge restores 4% maximum HP; a missed attack can still spend charges and trigger recovery.'],
  voidwalker:['to build a charge and mark the intended target.','only after checking the displayed health cost.','Reposition and recover health before committing again.','The charged cast costs up to 5% maximum HP, stopping at 1 HP. The damage bonus checks that you are above 1 HP at impact; incoming attacks can still defeat you.'],
  runesmith:['to gain a charge.','to attack and gain a class barrier.','Use the barrier to cover repositioning while your builder recovers.','Charge spending grants the barrier on cast even without a relic. An equipped relic adds damage only to charged finishers; barrier capacity remains capped at half maximum HP.'],
  alchemist:['to build a charge and mark the target.','against the marked target, preferably while missing health.','Rebuild charges and refresh the mark before the next burst.','Healing happens when charges are spent and is capped at full health. The armor-piercing bonus applies to the target marked at cast time; wait for the builder projectile to land.']
 };
 function guideDetails(item,target){
  const guide=guides[item.id];if(!guide)return;
  const beginner=document.createElement('details'),summary=document.createElement('summary'),steps=document.createElement('ol');summary.textContent='Suggested beginner sequence';beginner.className='rift-beginner-sequence';beginner.append(summary);
  for(const line of ['Use '+item.builder+' '+guide[0],'Use '+item.finisher+' '+guide[1],guide[2]]){const step=document.createElement('li');step.textContent=line;steps.append(step);}beginner.append(steps);
  const advanced=document.createElement('details'),heading=document.createElement('summary'),note=document.createElement('p');heading.textContent='Advanced timing';advanced.className='rift-advanced-timing';note.textContent=guide[3];advanced.append(heading,note);target.append(beginner,advanced);
 }
 function draw(select,target){
  const item=catalog.find(item=>item.id===select.value);target.replaceChildren();if(!item)return;
  const title=document.createElement('h3');title.textContent=item.base+' · '+item.name;target.append(title);
  const list=document.createElement('dl');for(const [label,value] of [['Resource',item.resource],['Builder',item.builder],['Finisher',item.finisher],['Brawl focus',focus[item.id]||'See equipped ability details for this combat style.']]){const term=document.createElement('dt'),description=document.createElement('dd');term.textContent=label;description.textContent=value;list.append(term,description);}target.append(list);guideDetails(item,target);
 }
 function render(){draw(left,document.getElementById('rift-compare-class-card-left'));draw(right,document.getElementById('rift-compare-class-card-right'));}
 function init(classes,current){
  catalog=(classes||[]).flatMap(base=>(base.subclasses||[]).map(sub=>({...sub,base:base.name})));
  for(const select of [left,right]){select.replaceChildren();for(const item of catalog){const option=document.createElement('option');option.value=item.id;option.textContent=item.base+' · '+item.name;select.append(option);}}
  left.value=catalog.some(item=>item.id===current)?current:catalog[0]?.id||'';right.value=catalog.find(item=>item.id!==left.value)?.id||left.value;render();root.hidden=!catalog.length;
 }
 left.addEventListener('change',render);right.addEventListener('change',render);
 window.RiftClassCompare={init,visibility(active){root.hidden=active||!catalog.length;}};
})();
