(function(global){
  'use strict';
  var W=global.ShopWorkbench,M=W.model,grid=document.getElementById('shopGrid');if(!grid)return;
  var surface=document.querySelector('.shop-console'),host=W.el('div');document.getElementById('shopAdvancedFilters').after(host);
  function parse(value){try{return JSON.parse(value||'{}');}catch(_){return {};}}
  function offer(card){var item=parse(card.querySelector('[data-item-inspect]').dataset.itemInspect),detail=parse(card.dataset.comparisonDetail);return {key:card.dataset.id,name:card.dataset.name,price:M.integer(card.dataset.price),currency:'gold',slot:card.dataset.slot,power:Number(card.dataset.power)||0,gain:Number(card.dataset.gain)||0,cr:Number(card.dataset.cr)||0,rarity:item.rarity||card.querySelector('.inv-meta').textContent.split('·')[0].trim(),element:card.dataset.element||item.element||'',item:item,detail:detail,node:card};}
  var offers=[],index=new Map(),sorts=[['value_price_desc','Highest price'],['value_name','Name A–Z'],['value_name_desc','Name Z–A'],['value_rarity','Highest rarity'],['value_cr','Highest combat rating'],['value_specials','Most special effects'],['value_xp','Highest XP bonus'],['value_regen','Highest regeneration'],['value_sockets','Most sockets']];
  var storeInputs=['shopSearch','shopSlot','shopSort','shopComparison','shopUpgrades','shopAffordable','shopStatCode','shopMinStat','shopPreserveStat','shopMinXP','shopMinRegen','shopMinSockets','shopSetFilter','shopEffectFilter'];
  var work=W.create({prefix:'sw',id:'shopWorkbench',user:grid.dataset.shopUser||'local',host:host,surface:surface,wallet:function(){return {gold:shopCurrentGold,tokens:0};},changed:function(){shopVisibleLimit=shopPageSize;sortShopStock();filterShopStock();if(global.shopQuickwinsChanged)shopQuickwinsChanged();summary();},capture:function(){var values={};storeInputs.forEach(function(id){var c=document.getElementById(id);values[id]=c.type==='checkbox'?c.checked:c.value;});return values;},restore:function(values){storeInputs.forEach(function(id){var c=document.getElementById(id);if(c.type==='checkbox')c.checked=values[id]===true;else if(typeof values[id]==='string')c.value=values[id];});},locate:function(o){if(!o)return;document.getElementById('shopReset').click();document.getElementById('shopSearch').value=o.name;shopFiltersChanged();o.node.scrollIntoView({block:'center'});o.node.querySelector('.shop-inspect-action').focus();}});
  var controls={};
  function add(id,label,type,choices){return controls[id]=work.input(id,label,type,choices);}
  add('Rarity','Rarity','select',[['','All rarities']]);add('Element','Element','select',[['','All elements']]);add('MinPrice','Minimum gold price','number');add('MaxPrice','Maximum gold price','number');add('MinPower','Minimum stat power','number');add('MinGain','Minimum power gain','number');add('NoLoss','No known stat losses','checkbox');add('Featured','Showcase relic','select',[['','All offers'],['only','Featured only'],['hide','Hide featured']]);add('WithinBudget','Within reserved budget','checkbox');add('WishlistOnly','Watchlist only','checkbox');add('PlanOnly','Planned offers only','checkbox');
  var syntax=W.el('small','Search words together, use "exact phrases", or -exclude a word. Accents and capitalization are ignored.');work.filters.appendChild(syntax);
  var discovery=W.el('p',null,'sw-annotation');discovery.id='swStockSummary';work.filters.appendChild(discovery);
  work.filters.append(W.button('Clear search',function(){document.getElementById('shopSearch').value='';shopFiltersChanged();}),W.button('Reset workbench filters',reset));
  var sort=document.getElementById('shopSort');sorts.forEach(function(pair){var option=W.el('option',pair[1]);option.value=pair[0];sort.appendChild(option);});
  var priorMatches=global.shopExtraMatches,priorSort=global.shopExtraSort;
  global.shopSearchMatches=function(text,query){return M.search(text,query);};
  function enough(id,n){return controls[id].value===''||n>=Number(controls[id].value);}
  global.shopExtraMatches=function(card){var o=index.get(card.dataset.id)||offer(card),d=o.detail;return (!priorMatches||priorMatches(card))&&(!controls.Rarity.value||o.rarity===controls.Rarity.value)&&(!controls.Element.value||o.element===controls.Element.value)&&enough('MinPrice',o.price)&&(controls.MaxPrice.value===''||o.price<=Number(controls.MaxPrice.value))&&enough('MinPower',o.power)&&enough('MinGain',o.gain)&&(!controls.NoLoss.checked||!d.unknown&&d.status!=='unknown'&&!(d.all_stats||d.changes||[]).some(function(s){return s.delta<0;}))&&(!controls.WithinBudget.checked||o.price<=work.spendable().gold)&&(!controls.WishlistOnly.checked||work.isWatched(o.key))&&(!controls.PlanOnly.checked||work.isPlanned(o.key))&&(controls.Featured.value!=='only'||card.classList.contains('featured-item'))&&(controls.Featured.value!=='hide'||!card.classList.contains('featured-item'));};
  var rarityOrder=['Common','Uncommon','Rare','Epic','Legendary','Mythic','Divine','Celestial','Eternal'];
  global.shopExtraSort=function(a,b,kind){var av=index.get(a.dataset.id)||offer(a),bv=index.get(b.dataset.id)||offer(b);switch(kind){case 'value_price_desc':return bv.price-av.price;case 'value_name':return av.name.localeCompare(bv.name);case 'value_name_desc':return bv.name.localeCompare(av.name);case 'value_rarity':return rarityOrder.indexOf(bv.rarity)-rarityOrder.indexOf(av.rarity);case 'value_cr':return bv.cr-av.cr;case 'value_specials':return (bv.item.specials||[]).length-(av.item.specials||[]).length;case 'value_xp':return (bv.item.xp_detail&&bv.item.xp_detail.effective_bonus_pct||0)-(av.item.xp_detail&&av.item.xp_detail.effective_bonus_pct||0);case 'value_regen':return (bv.item.regen_rate||0)-(av.item.regen_rate||0);case 'value_sockets':return (bv.item.sockets||0)-(av.item.sockets||0);default:return priorSort?priorSort(a,b,kind):0;}};
  function reset(){work.resetFilters();}
  function summary(){if(!offers.length)return;var prices=offers.map(function(o){return o.price;}),affordable=prices.filter(function(p){return p<=shopCurrentGold;});discovery.textContent='Loaded stock: '+W.fmt(Math.min.apply(null,prices))+'–'+W.fmt(Math.max.apply(null,prices))+' gold.'+(affordable.length?' Cheapest affordable: '+W.fmt(Math.min.apply(null,affordable))+' gold.':' No loaded offers are affordable.');}
  function lazyDetails(card){card.querySelectorAll('details.item-tools').forEach(function(box){if(box._swLazy)return;box._swLazy=true;var parked=document.createDocumentFragment();function sync(){if(box.open)box.appendChild(parked);else Array.from(box.children).forEach(function(node){if(node.tagName!=='SUMMARY')parked.appendChild(node);});}box.addEventListener('toggle',sync);sync();});}
  function refresh(){offers=shopCards.map(offer);index=new Map(offers.map(function(o){return [o.key,o];}));[['Rarity','rarity'],['Element','element']].forEach(function(pair){var c=controls[pair[0]],value=c.value;while(c.options.length>1)c.remove(1);Array.from(new Set(offers.map(function(o){return o[pair[1]];}).filter(Boolean))).sort().forEach(function(value){var option=W.el('option',value);option.value=value;c.appendChild(option);});c.value=value;});work.setOffers(offers);offers.forEach(function(o){lazyDetails(o.node);});summary();}
  global.ShopMainWorkbench={refresh:refresh,balanceChanged:function(){work.refresh();filterShopStock();summary();buffSummary();},receipt:function(message){work.receipt(message);}};
  document.getElementById('shopReset').addEventListener('click',reset);
  var recover=W.button('Reset filters',function(){document.getElementById('shopReset').click();});recover.id='swEmptyReset';document.getElementById('shopEmpty').after(recover);
  new MutationObserver(function(){recover.hidden=document.getElementById('shopEmpty').hidden;}).observe(document.getElementById('shopEmpty'),{attributes:true,attributeFilter:['hidden']});recover.hidden=true;
  function buffSummary(){document.querySelectorAll('.shop-buff-action').forEach(function(b){var input=document.getElementById('shopBuffAmount-'+b.dataset.kind),amount=M.integer(input.value),owned=M.integer(b.dataset.owned),output=document.getElementById('swBuffProjection-'+b.dataset.kind);if(!output)return;var cost=M.buffCost(owned,amount);output.textContent=amount<=0?'Choose an amount to preview the bonus increase.':cost===null?'Amount exceeds safe planning limits.':'Planned bonus increase: '+(amount/10).toFixed(1)+'%. Next token after this plan: '+W.fmt(M.buffCost(owned+amount,1))+' gold.';});}
  document.querySelectorAll('.shop-buff-action').forEach(function(b){var kind=b.dataset.kind,box=W.el('div',null,'sw-buff-planner'),input=document.getElementById('shopBuffAmount-'+kind);[1,5,10].forEach(function(n){box.appendChild(W.button('+'+n,function(){input.value=Math.min(Number.MAX_SAFE_INTEGER,M.integer(input.value)+n);input.dispatchEvent(new Event('input',{bubbles:true}));buffSummary();}));});var max=W.button('Max within budget',function(){var count=M.maxBuff(M.integer(b.dataset.owned),work.spendable().gold);if(!count){work.announce('The reserved budget cannot afford another '+kind+' token.');return;}input.value=count;input.dispatchEvent(new Event('input',{bubbles:true}));buffSummary();});max.id='swBuffMax-'+kind;box.appendChild(max);var output=W.el('p',null,'sw-annotation');output.id='swBuffProjection-'+kind;box.append(output,W.el('small',kind==='rarity'?'Rarity tokens improve future personalized stock quality; existing owned gear is unchanged.':'Quantity tokens expand personalized stock selection; they do not increase the quantity of a gear purchase.'));b.after(box);input.addEventListener('input',buffSummary);});
  var exchangeInput=document.getElementById('g2xAmount'),shortcutRow=W.el('div',null,'sw-exchange-shortcuts');
  [25,50,75,100].forEach(function(percent){var button=W.button(percent===100?'Maximum':percent+'%',function(){var amount=M.percentageAmount(work.spendable().gold,percent,goldPerXP);if(!amount){work.announce('This budget is below one complete exchange step.');return;}exchangeInput.value=amount;exchangeInput.dispatchEvent(new Event('input',{bubbles:true}));});button.setAttribute('aria-label','Preview '+percent+' percent of spendable gold');shortcutRow.appendChild(button);});
  exchangeInput.after(shortcutRow);shortcutRow.appendChild(W.el('small','Fills a preview only. The exact server review is still required.'));
  try{var savedSort=JSON.parse(sessionStorage.getItem('shopFilters')||'{}').sort;if(sorts.some(function(pair){return pair[0]===savedSort;}))sort.value=savedSort;}catch(_){}
  work.onChange(buffSummary);refresh();buffSummary();sortShopStock();filterShopStock();
})(window);
