ALTER TABLE users DROP COLUMN IF EXISTS weapon_id;
ALTER TABLE users DROP COLUMN IF EXISTS weapon_expires;

ALTER TABLE users DROP COLUMN IF EXISTS armor_id;
ALTER TABLE users DROP COLUMN IF EXISTS armor_expires;

ALTER TABLE users DROP COLUMN IF EXISTS relic_id;
ALTER TABLE users DROP COLUMN IF EXISTS relic_expires;
