ALTER TABLE users ADD COLUMN IF NOT EXISTS weapon_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weapon_expires TIMESTAMPTZ;

ALTER TABLE users ADD COLUMN IF NOT EXISTS armor_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS armor_expires TIMESTAMPTZ;

ALTER TABLE users ADD COLUMN IF NOT EXISTS relic_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS relic_expires TIMESTAMPTZ;
