ALTER TABLE users ADD COLUMN IF NOT EXISTS group_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cldbid INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_decay_date TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_days INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_poke_date TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_date TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS artifact_mult FLOAT NOT NULL DEFAULT 1.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS artifact_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS artifact_expires TIMESTAMPTZ;
