"""Generate lossless Brawl transport rows from the unchanged shared Abyss creature atlases."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import re
from PIL import Image


def validate_rows(rows):
    if len(rows)!=9 or rows[0]!=0 or rows[-1]!=1254 or any(type(value) is not int for value in rows) or any(a>=b for a,b in zip(rows,rows[1:])):
        raise ValueError('Review changed shared creature row layout')


def layout(root):
    text=(root/'abyss_combat_art.js').read_text(encoding='utf-8')
    def array(name):
        match=re.search(r'var '+name+r' = (\[.*?\]);',text,re.S)
        if not match:raise ValueError('Shared art layout missing: '+name)
        return match[1]
    rigs=re.findall(r"'([^']+)'",array('rigs'))
    assets=re.findall(r"'([^']+)'",array('atlasAssets'))
    rows=json.loads(array('atlasRows'))
    if len(rigs)!=32 or len(set(rigs))!=32 or len(assets)!=4 or len(set(assets))!=4 or len(rows)!=4:
        raise ValueError('Review changed shared creature atlas count')
    for boundaries in rows:validate_rows(boundaries)
    return rigs,assets,rows


def artifacts(root):
    rigs,assets,rows=layout(root)
    files,sources,sections={},{},{}
    for index,asset in enumerate(assets):
        raw=(root/Path(asset).name).read_bytes()
        with Image.open(io.BytesIO(raw)) as opened:original=opened.convert('RGBA')
        if original.size!=(1254,1254):raise ValueError('Review changed shared creature atlas dimensions')
        sources[asset]={'width':1254,'height':1254,'sha256':hashlib.sha256(raw).hexdigest()}
        for row in range(8):
            rig=rigs[index*8+row];start,end=rows[index][row:row+2]
            top,bottom=max(0,start-1),min(1254,end+1)
            crop=original.crop((0,top,1254,bottom))
            output=io.BytesIO();crop.save(output,format='PNG',optimize=True);encoded=output.getvalue()
            with Image.open(io.BytesIO(encoded)) as decoded:
                if decoded.convert('RGBA').tobytes()!=crop.tobytes():raise ValueError('Creature row encoding changed pixels')
            name='rift_creature_'+rig+'.png';files[name]=encoded
            sections[rig]={'sourceAsset':asset,'width':1254,'height':bottom-top,'top':top,'rowY':start,'rowHeight':end-start,
                           'url':'/static/'+name+'?v='+hashlib.sha256(encoded).hexdigest()[:12]}
    manifest={'version':1,'sources':sources,'rigs':sections}
    files['rift_creature_sections.js']=('// Generated by scripts/build-brawl-creature-sections.py; do not edit.\r\nwindow.RiftCreatureSections='+json.dumps(manifest,separators=(',',':'))+';\r\n').encode()
    return files


def build(root,check):
    files=artifacts(root)
    if check:
        stale=[name for name,data in files.items() if not (root/name).is_file() or (root/name).read_bytes()!=data]
        if stale:raise ValueError('Missing or stale creature rows: '+', '.join(stale))
    else:
        for name,data in files.items():(root/name).write_bytes(data)
    return len(files)

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    mode=parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write',action='store_true');mode.add_argument('--check',action='store_true')
    args=parser.parse_args()
    count=build(Path(__file__).resolve().parents[1]/'internal/bot/webassets',args.check)
    print(('Verified ' if args.check else 'Generated ')+str(count)+' creature transport assets')
