"""Build or verify lossless region transport panels without changing source artwork."""
import argparse
import hashlib
import io
import json
import math
from pathlib import Path
import re
from PIL import Image


def panel_geometry(size, rows):
    if size != (1058, 1487) or len(rows) != 6 or rows[0] != 0 or rows[-1] != 1 or any(a >= b for a, b in zip(rows, rows[1:])):
        raise ValueError('Review region transport for changed dimensions or layout')
    width, height = size
    panels = []
    for index in range(10):
        top, bottom = rows[index//2:index//2+2]
        x, y = index%2*(width//2), math.floor(top*height)
        right, end = x+width//2, math.ceil(bottom*height)
        panels.append({'x': x, 'y': y, 'width': right-x, 'height': end-y,
                       'source': [2, top*height+2-y, width/2-4, (bottom-top)*height-4]})
    return panels


def artifacts(root):
    source = (root / 'rift_renderer.js').read_text(encoding='utf-8')
    match = re.search(r'const regionRows = (\[[^\]]+\]);', source)
    if not match:
        raise ValueError('Renderer region layout was not found')
    rows = [float(value) for value in match[1].strip('[]').split(',')]
    raw = (root / 'rift_regions.png').read_bytes()
    with Image.open(io.BytesIO(raw)) as opened:
        original = opened.convert('RGBA')
    panels = panel_geometry(original.size, rows)
    files = {}
    for index, panel in enumerate(panels):
        x, y, width, height = (panel[key] for key in ('x','y','width','height'))
        crop = original.crop((x, y, x+width, y+height))
        output = io.BytesIO()
        crop.save(output, format='PNG', optimize=True)
        encoded = output.getvalue()
        with Image.open(io.BytesIO(encoded)) as decoded:
            if decoded.convert('RGBA').tobytes() != crop.tobytes():
                raise ValueError('Region encoding changed pixels')
        name = 'rift_region_'+str(index)+'.png'
        files[name] = encoded
        panel['url'] = '/static/'+name+'?v='+hashlib.sha256(encoded).hexdigest()[:12]
    manifest = {'version':1,'width':original.width,'height':original.height,
                'sourceSHA256':hashlib.sha256(raw).hexdigest(),'regions':panels}
    files['rift_region_sections.js'] = ('// Generated by scripts/build-brawl-region-sections.py; do not edit.\r\nwindow.RiftRegionSections='+json.dumps(manifest,separators=(',',':'))+';\r\n').encode()
    return files


def build(root, check):
    files = artifacts(root)
    if check:
        stale = [name for name, data in files.items() if not (root/name).is_file() or (root/name).read_bytes() != data]
        if stale:
            raise ValueError('Missing or stale region panels: '+', '.join(stale))
    else:
        for name, data in files.items():
            (root/name).write_bytes(data)
    return len(files)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write',action='store_true')
    mode.add_argument('--check',action='store_true')
    args = parser.parse_args()
    count = build(Path(__file__).resolve().parents[1]/'internal/bot/webassets', args.check)
    print(('Verified ' if args.check else 'Generated ')+str(count)+' region transport assets')
