"""Partition unchanged scenery props for transport at original drawing coordinates."""
import argparse
import hashlib
import io
import json
import math
from pathlib import Path
from PIL import Image


def artifacts(root):
    source=(root/'rift_renderer.js').read_text(encoding='utf-8')
    if "index=[0,1,2,3,4,5,6,3,3,7][run.level?.region||0],sw=img.width/4,sh=img.height/2" not in source:
        raise ValueError('Review changed prop region mapping or grid')
    raw=(root/'rift_props.png').read_bytes()
    with Image.open(io.BytesIO(raw)) as opened:original=opened.convert('RGBA')
    if original.size!=(1774,887):raise ValueError('Review changed prop atlas dimensions')
    files,panels={},[]
    for index in range(8):
        x,y=(index%4)*original.width/4,(index//4)*original.height/2
        left,top=max(0,math.floor(x)-1),max(0,math.floor(y)-1)
        right,bottom=min(original.width,math.ceil(x+original.width/4)+1),min(original.height,math.ceil(y+original.height/2)+1)
        crop=original.crop((left,top,right,bottom))
        output=io.BytesIO();crop.save(output,format='PNG',optimize=True);encoded=output.getvalue()
        with Image.open(io.BytesIO(encoded)) as decoded:
            if decoded.convert('RGBA').tobytes()!=crop.tobytes():raise ValueError('Prop encoding changed pixels')
        name='rift_prop_'+str(index)+'.png';files[name]=encoded
        panels.append({'left':left,'top':top,'width':right-left,'height':bottom-top,'url':'/static/'+name+'?v='+hashlib.sha256(encoded).hexdigest()[:12]})
    manifest={'version':1,'width':1774,'height':887,'sourceSHA256':hashlib.sha256(raw).hexdigest(),'regions':[0,1,2,3,4,5,6,3,3,7],'panels':panels}
    files['rift_prop_sections.js']=('// Generated by scripts/build-brawl-prop-sections.py; do not edit.\r\nwindow.RiftPropSections='+json.dumps(manifest,separators=(',',':'))+';\r\n').encode('utf-8')
    return files


def build(root,check):
    files=artifacts(root)
    if check:
        stale=[name for name,data in files.items() if not (root/name).is_file() or (root/name).read_bytes()!=data]
        if stale:raise ValueError('Missing or stale prop sections: '+', '.join(stale))
    else:
        for name,data in files.items():(root/name).write_bytes(data)
    return len(files)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    mode=parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write',action='store_true');mode.add_argument('--check',action='store_true')
    args=parser.parse_args()
    print(('Verified ' if args.check else 'Generated ')+str(build(Path(__file__).resolve().parents[1]/'internal/bot/webassets',args.check))+' prop transport assets')
