"""Build or check deterministic PNG transport rows; source artwork is never modified."""
import argparse
import hashlib
import importlib.util
import io
import json
from pathlib import Path

from PIL import Image

spec = importlib.util.spec_from_file_location("hero_sections", Path(__file__).with_name("measure-brawl-hero-sections.py"))
sections = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sections)


def artifacts(root):
    classes = sections.hero_classes(root)
    files, atlases = {}, {}
    for sheet_index, key in enumerate(["heroesA", "heroesB"]):
        stem = "rift_heroes_" + "ab"[sheet_index]
        raw = (root / (stem + ".png")).read_bytes()
        with Image.open(io.BytesIO(raw)) as opened:
            image = opened.convert("RGBA")
        if image.size != (2048, 768):
            raise ValueError("Review the transport layout for changed atlas dimensions")
        rows = []
        for index, row in enumerate(sections.split_rows(image, 6)):
            encoded = sections.encode_section(row, "PNG")
            name = stem + "_row" + str(index) + ".png"
            files[name] = encoded
            rows.append({"class": classes[sheet_index * 6 + index], "y": index * row.height,
                         "width": row.width, "height": row.height,
                         "url": "/static/" + name + "?v=" + hashlib.sha256(encoded).hexdigest()[:12]})
        atlases[key] = {"width": image.width, "height": image.height,
                        "sourceSHA256": hashlib.sha256(raw).hexdigest(), "rows": rows}
    manifest = {"version": 1, "atlases": atlases}
    files["rift_hero_sections.js"] = ("// Generated by scripts/build-brawl-hero-sections.py; do not edit.\r\n"
                                      "window.RiftHeroSections=" + json.dumps(manifest, separators=(",", ":")) + ";\r\n").encode()
    return files


def build(root, check):
    files = artifacts(root)
    if check:
        stale = [name for name, data in files.items() if not (root / name).is_file() or (root / name).read_bytes() != data]
        if stale:
            raise ValueError("Missing or stale generated sections: " + ", ".join(stale))
    else:
        for name, data in files.items():
            (root / name).write_bytes(data)
    return len(files)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    count = build(Path(__file__).resolve().parents[1] / "internal/bot/webassets", args.check)
    print(("Verified " if args.check else "Generated ") + str(count) + " hero section assets")
