"""Build deterministic transport rows without modifying local mob artwork."""
import argparse
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import re
from PIL import Image

spec = importlib.util.spec_from_file_location('atlas_sections', Path(__file__).with_name('measure-brawl-hero-sections.py'))
sections = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sections)

def artifacts(root):
    source = (root / 'rift_renderer.js').read_text(encoding='utf-8')
    match = re.search(r"const row = unit.id === 'player' \? index%6 : \(\{([^}]+)\}\[unit.kind\]", source)
    if not match:
        raise ValueError('Review changed local actor row mapping')
    mapping = re.findall(r'(\w+):(\d+)', match[1])
    if mapping != [('goblin','0'),('archer','1'),('knight','2'),('boss','3'),('wolf','4'),('spore','5')]:
        raise ValueError('Review changed local actor row order')
    raw = (root / 'rift_mobs.png').read_bytes()
    with Image.open(io.BytesIO(raw)) as opened:
        image = opened.convert('RGBA')
    if image.size != (2048,768):
        raise ValueError('Review changed local actor atlas dimensions')
    files, rows = {}, []
    for index, row in enumerate(sections.split_rows(image,6)):
        encoded = sections.encode_section(row,'PNG')
        name = 'rift_mobs_row'+str(index)+'.png'
        files[name] = encoded
        rows.append({'kind':mapping[index][0],'y':index*128,'width':2048,'height':128,'url':'/static/'+name+'?v='+hashlib.sha256(encoded).hexdigest()[:12]})
    manifest = {'version':1,'width':2048,'height':768,'sourceSHA256':hashlib.sha256(raw).hexdigest(),'rows':rows}
    files['rift_mob_sections.js'] = ('// Generated by scripts/build-brawl-mob-sections.py; do not edit.\r\nwindow.RiftMobSections='+json.dumps(manifest,separators=(',',':'))+';\r\n').encode('utf-8')
    return files

def build(root, check):
    files = artifacts(root)
    if check:
        stale = [name for name,data in files.items() if not (root/name).is_file() or (root/name).read_bytes()!=data]
        if stale:
            raise ValueError('Missing or stale local mob rows: '+', '.join(stale))
    else:
        for name,data in files.items():
            (root/name).write_bytes(data)
    return len(files)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write',action='store_true')
    mode.add_argument('--check',action='store_true')
    args = parser.parse_args()
    count = build(Path(__file__).resolve().parents[1]/'internal/bot/webassets',args.check)
    print(('Verified ' if args.check else 'Generated ')+str(count)+' local mob row assets')
